<template>
  <section>
    <v-btn
      fab
      color="white"
      href="https://github.com/FunkySheepStudio/"
      small
      target="_blank"
    >
      <v-icon
        large
      >
        mdi-github
      </v-icon>
    </v-btn>
    <v-btn
      fab
      small
      color="#BA68C8"
      href="https://discord.gg/9PWWDHPeJ9"
      target="_blank"
    >
      <v-icon
        medium
      >
        mdi-discord
      </v-icon>
    </v-btn>
    <v-btn
      fab
      small
      color="#E62117"
      href="https://www.youtube.com/channel/UCsJOvjzcYiil14bsKpZxgeA"
      target="_blank"
    >
      <v-icon
        large
      >
        mdi-youtube
      </v-icon>
    </v-btn>
    <v-btn
      fab
      small
      color="#f7931a"
      href="/studio/donate"
    >
      <v-icon
        large
      >
        mdi-bitcoin
      </v-icon>
    </v-btn>
  </section>
</template>
<script>
export default {
}
</script>
